//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.20 at 04:23:45 PM WIB 
//


package iseries.wsbeans.inqdata;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for inqdataResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="inqdataResult"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ACCTNBR" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ACCTTYPE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ADDRESS1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ADDRESS2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ADDRESS3" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ADDRESS4" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ADDRESS5" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CIF" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CTCOTHER" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DOB" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="FAXNBR" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="FULLNAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="HOMEPH" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="IDENTITY" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="KEYPARAM" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="MAIDENNAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="MOBILEPH" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="NPWP" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="OFFICEPH" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="POB" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PRIORITY" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="RESP" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ZIPCODE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "inqdataResult", propOrder = {
    "acctnbr",
    "accttype",
    "address1",
    "address2",
    "address3",
    "address4",
    "address5",
    "cif",
    "ctcother",
    "dob",
    "faxnbr",
    "fullname",
    "homeph",
    "identity",
    "keyparam",
    "maidenname",
    "mobileph",
    "npwp",
    "officeph",
    "pob",
    "priority",
    "resp",
    "zipcode"
})
public class InqdataResult {

    @XmlElement(name = "ACCTNBR", required = true)
    protected String acctnbr;
    @XmlElement(name = "ACCTTYPE", required = true)
    protected String accttype;
    @XmlElement(name = "ADDRESS1", required = true)
    protected String address1;
    @XmlElement(name = "ADDRESS2", required = true)
    protected String address2;
    @XmlElement(name = "ADDRESS3", required = true)
    protected String address3;
    @XmlElement(name = "ADDRESS4", required = true)
    protected String address4;
    @XmlElement(name = "ADDRESS5", required = true)
    protected String address5;
    @XmlElement(name = "CIF", required = true)
    protected String cif;
    @XmlElement(name = "CTCOTHER", required = true)
    protected String ctcother;
    @XmlElement(name = "DOB", required = true)
    protected String dob;
    @XmlElement(name = "FAXNBR", required = true)
    protected String faxnbr;
    @XmlElement(name = "FULLNAME", required = true)
    protected String fullname;
    @XmlElement(name = "HOMEPH", required = true)
    protected String homeph;
    @XmlElement(name = "IDENTITY", required = true)
    protected String identity;
    @XmlElement(name = "KEYPARAM", required = true)
    protected String keyparam;
    @XmlElement(name = "MAIDENNAME", required = true)
    protected String maidenname;
    @XmlElement(name = "MOBILEPH", required = true)
    protected String mobileph;
    @XmlElement(name = "NPWP", required = true)
    protected String npwp;
    @XmlElement(name = "OFFICEPH", required = true)
    protected String officeph;
    @XmlElement(name = "POB", required = true)
    protected String pob;
    @XmlElement(name = "PRIORITY", required = true)
    protected String priority;
    @XmlElement(name = "RESP", required = true)
    protected String resp;
    @XmlElement(name = "ZIPCODE", required = true)
    protected String zipcode;

    /**
     * Gets the value of the acctnbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCTNBR() {
        return acctnbr;
    }

    /**
     * Sets the value of the acctnbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCTNBR(String value) {
        this.acctnbr = value;
    }

    /**
     * Gets the value of the accttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCTTYPE() {
        return accttype;
    }

    /**
     * Sets the value of the accttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCTTYPE(String value) {
        this.accttype = value;
    }

    /**
     * Gets the value of the address1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADDRESS1() {
        return address1;
    }

    /**
     * Sets the value of the address1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADDRESS1(String value) {
        this.address1 = value;
    }

    /**
     * Gets the value of the address2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADDRESS2() {
        return address2;
    }

    /**
     * Sets the value of the address2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADDRESS2(String value) {
        this.address2 = value;
    }

    /**
     * Gets the value of the address3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADDRESS3() {
        return address3;
    }

    /**
     * Sets the value of the address3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADDRESS3(String value) {
        this.address3 = value;
    }

    /**
     * Gets the value of the address4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADDRESS4() {
        return address4;
    }

    /**
     * Sets the value of the address4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADDRESS4(String value) {
        this.address4 = value;
    }

    /**
     * Gets the value of the address5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADDRESS5() {
        return address5;
    }

    /**
     * Sets the value of the address5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADDRESS5(String value) {
        this.address5 = value;
    }

    /**
     * Gets the value of the cif property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCIF() {
        return cif;
    }

    /**
     * Sets the value of the cif property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCIF(String value) {
        this.cif = value;
    }

    /**
     * Gets the value of the ctcother property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCTCOTHER() {
        return ctcother;
    }

    /**
     * Sets the value of the ctcother property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCTCOTHER(String value) {
        this.ctcother = value;
    }

    /**
     * Gets the value of the dob property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDOB() {
        return dob;
    }

    /**
     * Sets the value of the dob property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDOB(String value) {
        this.dob = value;
    }

    /**
     * Gets the value of the faxnbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFAXNBR() {
        return faxnbr;
    }

    /**
     * Sets the value of the faxnbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFAXNBR(String value) {
        this.faxnbr = value;
    }

    /**
     * Gets the value of the fullname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFULLNAME() {
        return fullname;
    }

    /**
     * Sets the value of the fullname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFULLNAME(String value) {
        this.fullname = value;
    }

    /**
     * Gets the value of the homeph property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHOMEPH() {
        return homeph;
    }

    /**
     * Sets the value of the homeph property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHOMEPH(String value) {
        this.homeph = value;
    }

    /**
     * Gets the value of the identity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDENTITY() {
        return identity;
    }

    /**
     * Sets the value of the identity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDENTITY(String value) {
        this.identity = value;
    }

    /**
     * Gets the value of the keyparam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKEYPARAM() {
        return keyparam;
    }

    /**
     * Sets the value of the keyparam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKEYPARAM(String value) {
        this.keyparam = value;
    }

    /**
     * Gets the value of the maidenname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMAIDENNAME() {
        return maidenname;
    }

    /**
     * Sets the value of the maidenname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMAIDENNAME(String value) {
        this.maidenname = value;
    }

    /**
     * Gets the value of the mobileph property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOBILEPH() {
        return mobileph;
    }

    /**
     * Sets the value of the mobileph property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOBILEPH(String value) {
        this.mobileph = value;
    }

    /**
     * Gets the value of the npwp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNPWP() {
        return npwp;
    }

    /**
     * Sets the value of the npwp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNPWP(String value) {
        this.npwp = value;
    }

    /**
     * Gets the value of the officeph property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOFFICEPH() {
        return officeph;
    }

    /**
     * Sets the value of the officeph property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOFFICEPH(String value) {
        this.officeph = value;
    }

    /**
     * Gets the value of the pob property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOB() {
        return pob;
    }

    /**
     * Sets the value of the pob property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOB(String value) {
        this.pob = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRIORITY() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRIORITY(String value) {
        this.priority = value;
    }

    /**
     * Gets the value of the resp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRESP() {
        return resp;
    }

    /**
     * Sets the value of the resp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRESP(String value) {
        this.resp = value;
    }

    /**
     * Gets the value of the zipcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZIPCODE() {
        return zipcode;
    }

    /**
     * Sets the value of the zipcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZIPCODE(String value) {
        this.zipcode = value;
    }

}
