//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.25 at 11:33:55 AM WIB 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://inqdata.wsbeans.iseries/")
package iseries.wsbeans.inqdata;
